<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RaghuLaptop" ignored="0" name=" App Test Cases" tests="7" failures="2" timestamp="09 Jan 2021 12:34:17 GMT" time="22.155" errors="0">
  <testcase name="TestCaseID_1" time="2.844" classname="com.crm.qa.testcases.AppTestCases"/>
  <testcase name="TestCaseID_2" time="0.015" classname="com.crm.qa.testcases.AppTestCases">
    <skipped/>
  </testcase> <!-- TestCaseID_2 -->
  <testcase name="TestCaseID_2" time="0.01" classname="com.crm.qa.testcases.AppTestCases">
    <failure type="java.lang.AssertionError" message="expected [Web Orders sss] but found [Web Orders]">
      <![CDATA[java.lang.AssertionError: expected [Web Orders sss] but found [Web Orders]
	at com.crm.qa.pages.HomePage.verifyHomePageTitle(HomePage.java:70)
	at com.crm.qa.testcases.AppTestCases.TestCaseID_2(AppTestCases.java:25)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestCaseID_2 -->
  <testcase name="TestCaseID_3" time="5.791" classname="com.crm.qa.testcases.AppTestCases"/>
  <testcase name="TestCaseID_4" time="1.373" classname="com.crm.qa.testcases.AppTestCases"/>
  <testcase name="TestCaseID_5" time="0.004" classname="com.crm.qa.testcases.AppTestCases">
    <skipped/>
  </testcase> <!-- TestCaseID_5 -->
  <testcase name="TestCaseID_5" time="0.005" classname="com.crm.qa.testcases.AppTestCases">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.crm.qa.testcases.AppTestCases.TestCaseID_5(AppTestCases.java:55)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestCaseID_5 -->
</testsuite> <!--  App Test Cases -->
